name: app

# Runtime configuration for the application container
# https://docs.upsun.com/add-services/app-reference.html

# Use the PHP container (adjust version if needed)
type: "php:8.1"

# Root directory that should be served and how to handle requests
web:
  locations:
    "/":
      root: ""
      passthru: "/index.php"

# Declare the relationship to the MySQL service defined in services.yaml
relationships:
  database: "mysqldb:mysql"

# Optional shared mounts (good practice to provide tmp)
mounts:
  "tmp": "shared:files/tmp"
